apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indihu-web
  labels:
    name: indihu-web
    app: review-exec
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: indihu-web
        app: review-exec
    spec:
      containers:
        - name: indihu-web
          image: eu.gcr.io/inqool-1301/cz.inqool.indihu/web:latest
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: indihu-web
  labels:
    name: indihu-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    name: indihu-web
  clusterIP:

